### ISSUE TITLE
More mod compat!

### ISSUE THREAD

**Issue by Noire86** [TwentyOneZ/guardianchest#4]
Hey!

That would be awesome if GC would save  items from Aether 2 and Travellers` Gear mods.

Thanks! :)

**Comment by TwentyOneZ** [comment]
I will get into it as soon as I get spare time. =)

**Comment by TwentyOneZ** [comment]
Added support to Travellers' Gear in 1.5. But Aether 2 lacks an API, and I coudn't figure out  a way to manipulate its inventory. I don't see a way to implement it without an API. :(
